<?php

use Illuminate\Database\Seeder;

class MaintenancesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('maintenances')->insert([
			[
				'maintenance_code' => 'M000000001',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000002',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000003',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000004',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000005',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000006',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000007',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000008',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000009',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000010',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000011',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000012',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000013',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000014',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000015',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000016',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000017',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000018',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000019',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000020',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000021',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000022',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000023',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 21,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000024',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 20,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000025',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 19,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000026',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 18,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000027',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 17,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000028',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 16,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000029',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 15,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000030',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 14,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000031',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 13,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000032',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 12,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000033',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 11,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000034',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 10,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000035',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 9,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000036',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 2,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000037',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 2,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000038',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 2,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000039',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 2,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000040',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 8,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000041',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 7,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000042',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 6,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000043',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 5,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000044',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 4,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000045',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => '壊れた',
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 3,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000046',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'エアコン',
				'manufacturer' => 'パナソニック',
				'model_number' => 'JWE-680A',
				'order_type_id' => 3,
				'when' => '昨日',
				'situation' => '電源が入らない。',
				'order' => 'エアコン パナソニック JWE-680A 電源が入らない。修繕お願いします。',
				'remark' => null,
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 2,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000047',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'コーヒーマシン','manufacturer' => 'ラッキーコーヒーマシン',
				'model_number' => 'A400',
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => 'コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'order' => 'コーヒーマシン ラッキーコーヒーマシン A400 コーヒーの味が一定ではない上、ラテ類を作る時ミルクが出てこない。',
				'remark' => '',
				'is_emergency' => 1,
				'is_disaster' => 1,
				'progress_id' => 1,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000048',
				'shop_id' => 7,
				'applicant_id' => 10,
				'equipment' => 'シンクフタ','manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '見積もり後、修繕費が○○円の場合は設備を入れ替える',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 1,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000049',
				'shop_id' => 9,
				'applicant_id' => 8,
				'equipment' => 'シンクフタ',
				'manufacturer' => 'KAKUDAI',
				'model_number' => '4520-5',
				'order_type_id' => 2,
				'when' => '今朝',
				'situation' => null,
				'order' => 'シンクフタ KAKUDAI 4520-5 納品手配お願いいたします。',
				'remark' => '',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 1,
				'completed_date' => null,
			],
			[
				'maintenance_code' => 'M000000050',
				'shop_id' => 9,
				'applicant_id' => 8,
				'equipment' => 'オートウェイター',
				'manufacturer' => 'カコー',
				'model_number' => null,
				'order_type_id' => 1,
				'when' => '今朝',
				'situation' => null,
				'order' => 'オートウェイター カコー 設備修繕の見積り',
				'remark' => '',
				'is_emergency' => 0,
				'is_disaster' => 0,
				'progress_id' => 1,
				'completed_date' => null,
			],
		]);
    }
}
